# Generated by Django 3.2.5 on 2021-12-04 15:20

import createTask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[createTask.models.empty_validator])),
                ('type', models.IntegerField(validators=[createTask.models.empty_validator])),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField(validators=[createTask.models.empty_validator])),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
